### ISSUE TITLE
`inout-merge` ICE in compiler

### ISSUE THREAD

**Issue by utaal** [secure-foundations/dafny#16]
Repro:

```
// path/to/Scripts/dafny /compile:0 /noVerify /spillTargetCode:3 /countVerificationErrors:0 /out:out.tmp except_repro.dfy

module Test {
  type {:extern "predefined"} lseq<A>

  type Key
  type Value

  linear datatype Node =
    | Leaf(linear keys: seq<Key>, linear values: seq<Value>)
    | Index(linear pivots: seq<Key>, linear children: lseq<Node>)

  method Test(linear index: Node) returns (linear index': Node)
  requires index.Index?
  {
    linear var Index(pivots, children) := index; // <- offending line
    index' := Index(pivots, children);
  }
}
```

**Comment by tjhance** [comment]
```
$ daf /compile:0 /noVerify /spillTargetCode:3 /countVerificationErrors:0 /out:out.tmp moo.dfy 
Dafny 3.0.0.21209

Dafny program verifier did not attempt verification
/Users/thance/sandbox/moo.dfy(6,7): Error: Opaque type ('Test_Compile.Key') cannot be compiled; perhaps make it a type synonym or use :extern.
/Users/thance/sandbox/moo.dfy(7,7): Error: Opaque type ('Test_Compile.Value') cannot be compiled; perhaps make it a type synonym or use :extern.
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.Dafny.Compiler.TrCasePatternOpt[VT](CasePattern`1 pat, Expression rhs, String rhs_string, Type rhsType, IToken rhsTok, TargetWriter wr, Boolean inLetExprBody) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/Dafny/Compiler.cs:line 2161
   at Microsoft.Dafny.Compiler.TrCasePatternOpt[VT](CasePattern`1 pat, Expression rhs, TargetWriter wr, Boolean inLetExprBody) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/Dafny/Compiler.cs:line 2103
   at Microsoft.Dafny.Compiler.TrStmt(Statement stmt, TargetWriter wr) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/Dafny/Compiler.cs:line 3118
   at Microsoft.Dafny.Compiler.TrStmtList(List`1 stmts, TargetWriter writer) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/Dafny/Compiler.cs:line 4140
   at Microsoft.Dafny.Compiler.CompileMethod(Method m, IClassWriter cw, Boolean lookasideBody) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/Dafny/Compiler.cs:line 2080
   at Microsoft.Dafny.Compiler.CompileClassMembers(TopLevelDeclWithMembers c, IClassWriter classWriter) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/Dafny/Compiler.cs:line 1644
   at Microsoft.Dafny.Compiler.Compile(Program program, TargetWriter wrx) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/Dafny/Compiler.cs:line 1202
   at Microsoft.Dafny.DafnyDriver.CompileDafnyProgram(Program dafnyProgram, String dafnyProgramName, ReadOnlyCollection`1 otherFileNames, Boolean invokeCompiler, TextWriter outputWriter) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 663
   at Microsoft.Dafny.DafnyDriver.Compile(String fileName, ReadOnlyCollection`1 otherFileNames, Program dafnyProgram, PipelineOutcome oc, Dictionary`2 statss, Boolean verified) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 451
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 285
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 58
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass1_0.<Main>b__0() in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 34
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
/Users/thance/Dropbox/veribetrfs/.dafny/dafny/Binaries/dafny: line 34: 38192 Abort trap: 6           "$DOTNET" "$DAFNY" "$@"

real	0m1.743s
user	0m1.135s
sys	0m0.177s
```

**Comment by utaal** [comment]
Fixed on master https://github.com/dafny-lang/dafny/pull/1081

**Comment by parno** [comment]
Fixed in `inout-merge` due to merging in official Dafny master.
