### ISSUE TITLE
unable to compile veribetrfs master

### ISSUE THREAD

**Issue by jialin-li** [secure-foundations/dafny#20]
When compiling veribetrfs/master ([this commit](https://github.com/splatlab/veribetrfs/commit/7ff97b4cd41c9fcd50761d5bfc3a844e2897eb35)) with the [latest commit](https://github.com/secure-foundations/dafny/commit/2002a5a4e898b099a08693ad08ad9cb1dab0488f) on dafny/betr, the dafny compiler terminates due to an assertion failure.

The command used for compilation is `make elf`, which executes `.dafny/dafny//Scripts/dafny /compile:0 /noVerify /spillTargetCode:3 /countVerificationErrors:0 /out:/path/veribetrfs/build/Bundle-i.cpp /compileTarget:cpp Impl/Bundle.i.dfy Framework.h`

The output is:

/veribetrfs/Impl/../lib/Buckets/../DataStructures/BtreeModel.i.dfy KMBtreeModel (1108,4): Error: an assume statement cannot be compiled
Process terminated. Assertion failed.
   at Microsoft.Dafny.Compiler.TrCallStmt(CallStmt s, String receiverReplacement, TargetWriter wr) in /veribetrfs/.dafny/dafny/Source/Dafny/Compiler.cs:line 3965
   at Microsoft.Dafny.Compiler.TrStmt(Statement stmt, TargetWriter wr) in /veribetrfs/.dafny/dafny/Source/Dafny/Compiler.cs:line 2733
   at Microsoft.Dafny.Compiler.TrStmt(Statement stmt, TargetWriter wr) in /veribetrfs/.dafny/dafny/Source/Dafny/Compiler.cs:line 2642
   at Microsoft.Dafny.Compiler.TrStmtList(List1 stmts, TargetWriter writer) in /veribetrfs/.dafny/dafny/Source/Dafny/Compiler.cs:line 4042
   at Microsoft.Dafny.Compiler.CompileMethod(Program program, Method m, IClassWriter cw, Boolean lookasideBody) in /veribetrfs/.dafny/dafny/Source/Dafny/Compiler.cs:line 2200
   at Microsoft.Dafny.Compiler.CompileClassMembers(Program program, TopLevelDeclWithMembers c, IClassWriter classWriter) in /veribetrfs/.dafny/dafny/Source/Dafny/Compiler.cs:line 1764
   at Microsoft.Dafny.Compiler.Compile(Program program, TargetWriter wrx) in /veribetrfs/.dafny/dafny/Source/Dafny/Compiler.cs:line 1179
   at Microsoft.Dafny.DafnyDriver.CompileDafnyProgram(Program dafnyProgram, String dafnyProgramName, ReadOnlyCollection1 otherFileNames, Boolean invokeCompiler, TextWriter outputWriter) in /veribetrfs/.dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 662
   at Microsoft.Dafny.DafnyDriver.Compile(String fileName, ReadOnlyCollection1 otherFileNames, Program dafnyProgram, PipelineOutcome oc, Dictionary2 statss, Boolean verified) in /veribetrfs/.dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 438
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList1 dafnyFiles, ReadOnlyCollection1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /veribetrfs/.dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 278
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /veribetrfs/.dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 60
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass1_0.<Main>b__0() in /work/veribetrfs/.dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 36
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
.dafny/dafny//Scripts/dafny: line 34:   456 Aborted                 (core dumped) "$DOTNET" "$DAFNY" "$@"
Command exited with non-zero status 134
9.46user 0.10system 0:09.25elapsed 103%CPU (0avgtext+0avgdata 413216maxresident)k
0inputs+0outputs (0major+99223minor)pagefaults 0swaps
Makefile:274: recipe for target 'build/Bundle.cpp' failed
make: *** [build/Bundle.cpp] Error 134

**Comment by parno** [comment]
It looks like the proximate cause of this crash is due to a failing Contract assertion inside of `Compiler.cs` (line 3965).  

The related source line of code is line 552 in `Impl/IndirectionTable.i.dfy`, namely:
```
UpdatePredCounts(inout self, ref, [], oldEntry.value.succs);
```
and `ref` is the problematic argument.  From what I can see, `ref` has type `BT.G.Reference`, but Dafny is processing it as the second formal argument of `UpdatePredCounts`, namely `newSuccs: seq<BT.G.Reference>`, which obviously has the wrong type to line up here.  

My best guess is that either `UpdatePredCounts` needs to be called in a different fashion (see e.g., line 1010), or that this is an example of the inout rewrite not putting things back the way Dafny expects them.  Perhaps @utaal can shed some light on this?

**Comment by jialin-li** [comment]
I updated line 552 to `inout self.UpdatePredCounts(ref, [], oldEntry.value.succs);`, still seeing the crash, will look into it more

**Comment by utaal** [comment]
It turns out this isn't incorrect compiler behaviour, but a failure in disallowing incorrect syntax.
The correct syntax to call `linear inout` method members is `inout self.Method(...)`, but the veribetrfs code base had some `Method(inout self, ...)` call sites. These are incorrectly accepted by the `inout` code and crash the compiler.

Changing the call sites has resolved the issue in veribetrfs, I'm looking into disallowing the incorrect syntax at the (pre-)resolver stage.

**Comment by parno** [comment]
Cool, thanks for tracking that down!
