### ISSUE TITLE
exception on module argument name collision

### ISSUE THREAD

**Issue by tjhance** [secure-foundations/dafny#34]
This is probably a minor issue, but filing for completeness. Could be a symptom of something deeper, I guess.

```
abstract module Ifc {
  type Op
}

abstract module StateMachine(Ifc: Ifc) {
  type Variables
  predicate Init(s: Variables)
  predicate Next(s: Variables, s': Variables, op: Ifc.Op)
}

// Async state machines

abstract module InputOutputIfc refines Ifc {
  type Input
  type Output

  datatype Op = Op(input: Input, output: Output)
}

module AsyncIfc(Ifc: InputOutputIfc) refines Ifc {
}
```

gives an exception

```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.Dafny.AliasModuleDecl' to type 'Microsoft.Dafny.LiteralModuleDecl'.
   at Microsoft.Dafny.ModuleQualifiedId.Set(ModuleDecl m) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/Dafny/DafnyAst.cs:line 4139
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/Dafny/Resolver.cs:line 512
   at Microsoft.Dafny.Main.Resolve(Program program, ErrorReporter reporter) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/Dafny/DafnyMain.cs:line 169
   at Microsoft.Dafny.Main.ParseCheck(IList`1 files, String programName, ErrorReporter reporter, Program& program) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/Dafny/DafnyMain.cs:line 117
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 268
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 60
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass1_0.<Main>b__0() in /Users/thance/Dropbox/veribetrfs/.dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 36
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

The issue here is the collision of the Ifc names (workaround is just to rename one of them).

**Comment by parno** [comment]
Mostly fixed by bd8f3e7
